version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ratingpredictor
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - "5430:5432"